services:
  accounts:
    image: "joaovitormoraveis/ms-accounts:0.0.1"
    container_name: "ms-accounts"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - udemycourse
  loans:
    image: "joaovitormoraveis/ms-loan:0.0.1"
    container_name: "ms-loans"
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - udemycourse
  cards:
    image: "joaovitormoraveis/ms-cards:0.0.1"
    container_name: "ms-cards"
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - udemycourse

networks:
  udemycourse:
    driver: "bridge"


